<a href="https://colab.research.google.com/github/S-Devisri01/Python-colab/blob/main/Python_gen_ai_DL_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ======================================
# DAY 1 – DEEP LEARNING (PERCEPTRON)
# MULTILAYER PERCEPTRON (Simple Network)
# ======================================

# 🎬 Example 1: Simple Perceptron Logic
# Computer decides if you’ll enjoy a movie

# Inputs (1 = Yes, 0 = No)
likes_action = 1
likes_comedy = 0
likes_romance = 1

# Layer 1 (manual neurons)
neuron1 = (likes_action * 0.8) + (likes_comedy * 0.1) + (likes_romance * 0.3)
neuron2 = (likes_action * 0.2) + (likes_comedy * 0.9) + (likes_romance * 0.4)

print("\nNeuron 1 Output:", round(neuron1, 2))
print("Neuron 2 Output:", round(neuron2, 2))


# ======================================
# Example 2: Multilayer Perceptron (MLP)
# Real Neural Network using sklearn
# ======================================

from sklearn.neural_network import MLPClassifier

# Training data
# Inputs → [dark_clouds, humidity, forecast_rain]
X = [
    [1, 1, 0],  # raining likely
    [0, 1, 0],  # cloudy but no rain
    [1, 0, 1],  # dark + forecast rain
    [0, 0, 0]   # clear weather
]

# Output labels
# 1 = Take umbrella, 0 = Don’t take umbrella
y = [1, 0, 1, 0]

# Create and train the neural network
model = MLPClassifier(
    hidden_layer_sizes=(2,),
    max_iter=500,
    random_state=42
)

model.fit(X, y)

# Display learned parameters
print("\nHidden Layer Weights:\n", model.coefs_[0])
print("Hidden Layer Bias:\n", model.intercepts_[0])
print("Output Layer Weights:\n", model.coefs_[1])
print("Output Layer Bias:\n", model.intercepts_[1])

# ======================================
# Testing a new condition
# ======================================

# New input → dark, humid, forecast rain = YES
test_data = [[1, 1, 1]]

prediction = model.predict(test_data)[0]

print("\n🤖 ANN Prediction:",
      "Take Umbrella ☔" if prediction == 1 else "No Umbrella Needed 🌤️")



Neuron 1 Output: 1.1
Neuron 2 Output: 0.6

Hidden Layer Weights:
 [[-0.01242151  1.46746895]
 [ 0.13638037 -0.07362518]
 [-0.33674608 -0.27450885]]
Hidden Layer Bias:
 [-0.9681903  0.813466 ]
Output Layer Weights:
 [[0.01544123]
 [1.00772222]]
Output Layer Bias:
 [-1.31548103]

🤖 ANN Prediction: Take Umbrella ☔


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [1]:
# ============================================================
# 🌦️ ARTIFICIAL NEURAL NETWORK – COMPLETE WEATHER PROJECT
# ============================================================
# TOPICS COVERED
# 1. Weather Dataset
# 2. Perceptron & Limitation
# 3. Multilayer Perceptron (MLP)
# 4. Forward Propagation
# 5. Activation Functions
# 6. Loss Functions
# 7. Gradient Descent Intuition
# ============================================================


# ======================
# 📦 IMPORT LIBRARIES
# ======================
import numpy as np
import pandas as pd

from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler


# ============================================================
# 1️⃣ CREATE WEATHER DATASET
# ============================================================
# Features:
# Temperature (°C)
# Humidity (%)
# Windy (0 = No, 1 = Yes)
# Target:
# Rain (1 = Yes, 0 = No)

data = {
    "Temperature": [30, 25, 28, 35, 20, 18, 22, 33, 27, 24],
    "Humidity":    [70, 80, 65, 90, 85, 75, 60, 95, 78, 68],
    "Windy":       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    "Rain":        [1, 1, 0, 1, 0, 0, 0, 1, 1, 0]
}

df = pd.DataFrame(data)

print("\n📊 WEATHER DATASET")
print(df)

# Split inputs and target
X = df[["Temperature", "Humidity", "Windy"]]
y = df["Rain"]


# ============================================================
# 2️⃣ PERCEPTRON (SINGLE NEURON)
# ============================================================
print("\n🔴 PERCEPTRON MODEL")

perceptron = Perceptron(max_iter=1000, random_state=42)
perceptron.fit(X, y)

perceptron_predictions = perceptron.predict(X)

print("Perceptron Predictions:", perceptron_predictions)
print("""
⚠️ Limitation:
Perceptron can only learn LINEAR patterns.
Fails when data is complex or non-linear.
""")


# ============================================================
# 3️⃣ MULTILAYER PERCEPTRON (MLP)
# ============================================================
print("\n🟢 MULTILAYER PERCEPTRON (MLP)")

# Feature scaling (VERY important for neural networks)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

mlp = MLPClassifier(
    hidden_layer_sizes=(3,),
    activation='relu',
    max_iter=2000,
    random_state=42
)

mlp.fit(X_scaled, y)

mlp_predictions = mlp.predict(X_scaled)
print("MLP Predictions:", mlp_predictions)

print("""
✅ MLP Advantage:
• Multiple neurons
• Activation functions
• Learns NON-LINEAR patterns
""")


# ============================================================
# 4️⃣ FORWARD PROPAGATION (PROBABILITIES)
# ============================================================
print("\n➡️ FORWARD PROPAGATION OUTPUT (Probabilities)")

probabilities = mlp.predict_proba(X_scaled)
print(np.round(probabilities, 3))

print("""
Each row represents:
[ Probability(No Rain), Probability(Rain) ]
""")


# ============================================================
# 5️⃣ ACTIVATION FUNCTIONS
# ============================================================
print("\n⚡ ACTIVATION FUNCTIONS")

x = np.array([-3, -1, 0, 1, 3])

relu = np.maximum(0, x)
sigmoid = 1 / (1 + np.exp(-x))
tanh = np.tanh(x)

print("Input:   ", x)
print("ReLU:    ", relu)
print("Sigmoid: ", np.round(sigmoid, 3))
print("Tanh:    ", np.round(tanh, 3))

print("""
Activation Purpose:
• ReLU → Hidden layers
• Sigmoid → Binary output
• Tanh → Centered data
""")


# ============================================================
# 6️⃣ LOSS FUNCTIONS
# ============================================================
print("\n📉 LOSS FUNCTIONS")

# Mean Squared Error (example)
y_true = np.array([1, 0, 1])
y_pred = np.array([0.8, 0.2, 0.6])

mse = np.mean((y_true - y_pred) ** 2)
print("Mean Squared Error (MSE):", round(mse, 3))


# ============================================================
# 7️⃣ GRADIENT DESCENT INTUITION
# ============================================================
print("\n⛰️ GRADIENT DESCENT DEMO")

# Simple linear relation: y = 2x
X_gd = np.array([1, 2, 3])
y_gd = np.array([2, 4, 6])

w = 0.5        # Initial weight
lr = 0.1       # Learning rate

for step in range(4):
    y_pred_gd = w * X_gd
    loss = np.mean((y_gd - y_pred_gd) ** 2)

    gradient = -2 * np.mean(X_gd * (y_gd - y_pred_gd))
    w = w - lr * gradient

    print(f"Step {step + 1} | Weight: {w:.3f} | Loss: {loss:.3f}")

print("""
Gradient Descent:
• Calculates error
• Finds direction to reduce error
• Updates weights step by step
""")



📊 WEATHER DATASET
   Temperature  Humidity  Windy  Rain
0           30        70      0     1
1           25        80      1     1
2           28        65      0     0
3           35        90      1     1
4           20        85      0     0
5           18        75      1     0
6           22        60      0     0
7           33        95      1     1
8           27        78      0     1
9           24        68      1     0

🔴 PERCEPTRON MODEL
Perceptron Predictions: [1 1 1 1 1 1 1 1 1 1]

⚠️ Limitation:
Perceptron can only learn LINEAR patterns.
Fails when data is complex or non-linear.


🟢 MULTILAYER PERCEPTRON (MLP)
MLP Predictions: [1 1 0 1 0 0 0 1 1 0]

✅ MLP Advantage:
• Multiple neurons
• Activation functions
• Learns NON-LINEAR patterns


➡️ FORWARD PROPAGATION OUTPUT (Probabilities)
[[0.162 0.838]
 [0.083 0.917]
 [0.86  0.14 ]
 [0.    1.   ]
 [0.618 0.382]
 [0.969 0.031]
 [0.994 0.006]
 [0.    1.   ]
 [0.09  0.91 ]
 [0.962 0.038]]

Each row represents:
[ Probability(N