<a href="https://colab.research.google.com/github/S-Devisri01/Python-colab/blob/main/Python_gen_ai_day4%2C5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1=np.array([10,20,30,40,50])
arr2=np.array([1,2,3,4,5])
print("Original:",(arr1+arr2))

#python list
list1=[1,2,3]
list2=[10,20,30,40,50]

#element wise addition with list-you need a loop
result_list=[list1[i]+list2[i] for i in range(len(list1))]
print("list value:",result_list)

Original: [11 22 33 44 55]
list value: [11, 22, 33]


In [ ]:
#array dimension creation

# 1D array
arr1=np.array([1,2,3])
print("1D Array:",arr1)

# 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr2)

#array filled with zero
zeros=np.zeros((4,4))
print("Zeros:\n",zeros)

#array filled with ones
ones=np.ones((2,3))
print("Ones:\n",ones)

#random array
rand=np.random.rand(2,3)
print("Random Array:\n",rand)

#range array # start 0, stop 10, step 3
r=np.arange(0,10,3)
print("Range:\n",r)

#Array operation: numpy
import numpy as np
arr=np.array([10,20,30,40,50])

print("Original:",arr)
print("Add:",arr+5)
print("Multiply by 2:",arr*2)
print("Square:",arr**2)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random Array:
 [[0.26105049 0.37538217 0.17274697]
 [0.67572581 0.36981238 0.69743703]]
Range:
 [0 3 6 9]
Original: [10 20 30 40 50]
Add: [15 25 35 45 55]
Multiply by 2: [ 20  40  60  80 100]
Square: [ 100  400  900 1600 2500]


In [ ]:
# NUMPY BASICS
import numpy as np

# 1️ NumPy, List (Salary Example)
print("\n--- NumPy (Salary) ---")
salary_np = np.array([10000, 15000, 20000])
print("NumPy Salary + Bonus:", salary_np + 2000)

# 2️ List, NumPy Addition (Marks Example)
print("\n--- List NumPy Addition (Marks) ---")
marks_sem1 = [70, 80, 90]
marks_sem2 = [5, 10, 5]
total_list = [marks_sem1[i] + marks_sem2[i] for i in range(len(marks_sem1))]
print("List Addition:", total_list)

marks1_np = np.array([70, 80, 90])
marks2_np = np.array([5, 10, 5])
print("NumPy Addition:", marks1_np + marks2_np)

# 3️ Array Creation
print("\n--- Array Creation ---")
steps = np.array([3000, 4000, 5000])
print("1D Array (Steps):", steps)

student_marks = np.array([[85, 90, 88],[78, 82, 80]])
print("2D Array (Student Marks):\n", student_marks)

attendance = np.zeros((2, 3))
print("Attendance (Zeros):\n", attendance)

present = np.ones((2, 2))
print("All Present (Ones):\n", present)

roll_numbers = np.arange(2, 11, 2)
print("Even Roll Numbers:", roll_numbers)

random_scores = np.random.rand(2, 3)
print("Random Scores:\n", random_scores)

# 4️ Array Operations (Shopping Prices)
print("\n--- Array Operations (Shopping) ---")
prices = np.array([100, 200, 300])
print("Original Prices:", prices)
print("After Discount:", prices - 50)
print("Double Price:", prices * 2)
print("Squared Prices:", prices ** 2)

# 5️ Statistics (Exam Marks)
print("\n--- Statistics ---")
exam_marks = np.array([65, 75, 85, 95])
print("Total Marks:", np.sum(exam_marks))
print("Average Marks:", np.mean(exam_marks))
print("Highest Mark:", np.max(exam_marks))
print("Topper Index:", np.argmax(exam_marks))

# 6️ Matrix Operations (Classroom Seating)
print("\n--- Matrix Operations ---")
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print("Matrix Addition:\n", A + B)
print("Matrix Multiplication:\n", np.dot(A, B))
print("Matrix Transpose:\n", A.T)

# 7️ Slicing (Mobile Screen Time)
print("\n--- Slicing ---")
screen_time = np.array([1, 2, 3, 4, 5])
print("First Day Screen Time:", screen_time[0])
print("Last Day Screen Time:", screen_time[-1])
print("Middle Days Screen Time:", screen_time[1:4])

print("\n--- Program Ended Successfully ---")


--- NumPy (Salary) ---
NumPy Salary + Bonus: [12000 17000 22000]

--- List NumPy Addition (Marks) ---
List Addition: [75, 90, 95]
NumPy Addition: [75 90 95]

--- Array Creation ---
1D Array (Steps): [3000 4000 5000]
2D Array (Student Marks):
 [[85 90 88]
 [78 82 80]]
Attendance (Zeros):
 [[0. 0. 0.]
 [0. 0. 0.]]
All Present (Ones):
 [[1. 1.]
 [1. 1.]]
Even Roll Numbers: [ 2  4  6  8 10]
Random Scores:
 [[0.61655564 0.63087842 0.32492595]
 [0.70680597 0.80649909 0.56935183]]

--- Array Operations (Shopping) ---
Original Prices: [100 200 300]
After Discount: [ 50 150 250]
Double Price: [200 400 600]
Squared Prices: [10000 40000 90000]

--- Statistics ---
Total Marks: 320
Average Marks: 80.0
Highest Mark: 95
Topper Index: 3

--- Matrix Operations ---
Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Transpose:
 [[1 3]
 [2 4]]

--- Slicing ---
First Day Screen Time: 1
Last Day Screen Time: 5
Middle Days Screen Time: [2 3 4]

--- Program Ended Successfu

In [3]:
#pandas
import pandas as pd
data = {
    "Employee": ["Arun", "Divya", "Karthik", "Meena", "Ravi"],
    "Sales": [45000, 52000, None, 61000, 48000],
    "Region": ["South", "North", "East", "West", "South"]
}
df = pd.DataFrame(data)
#remove duplicate
df=df.drop_duplicates()
print("\n Remove duplicate")
print(df)
# add colum
df["Age"]=[20,24,21,22,25]
print("\n Add new column")
print(df)
#filter sales
high_sales=df[df["Sales"]>45000]
print("\n High Sales")
print(high_sales)
#filer region
south_sales=df[df["Region"]=="South"]
print("\n Specific region")
print(south_sales)
#rename
df=df.rename(columns={"Employee": "Name"})
print("\n Rename")
print(df)
#fill NA
df["Sales"]=df["Sales"].fillna(0)
print("\n Fill NA")
print(df)
# east region with high sales
east_high_sales = df[(df["Region"] == "East") & (df["Sales"] > 45000)]
print("\n East region high sales")
print(east_high_sales)
# total sales
total_sales = df["Sales"].sum()
print("\n Total Sales")
print(total_sales)
# average sales
avg_sales = df["Sales"].mean()
print("\n Average Sales")
print(avg_sales)
# group by region
region_sales = df.groupby("Region")["Sales"].sum()
print("\n Group by Region")
print(region_sales)
# head
print("\n Head function")
print(df.head())
# info
print("\n Info function")
print(df.info())
# describe
print("\n Describe function")
print(df.describe())
#save file
load_csv=df.to_csv("New_data.csv",index=False)
# upload a excel file
# sales_data=pd.read_excel("/content/sales_data (Not used still).xlsx")
# print("\n Read the excel file","\n",sales_data)


 Remove duplicate
  Employee    Sales Region
0     Arun  45000.0  South
1    Divya  52000.0  North
2  Karthik      NaN   East
3    Meena  61000.0   West
4     Ravi  48000.0  South

 Add new column
  Employee    Sales Region  Age
0     Arun  45000.0  South   20
1    Divya  52000.0  North   24
2  Karthik      NaN   East   21
3    Meena  61000.0   West   22
4     Ravi  48000.0  South   25

 High Sales
  Employee    Sales Region  Age
1    Divya  52000.0  North   24
3    Meena  61000.0   West   22
4     Ravi  48000.0  South   25

 Specific region
  Employee    Sales Region  Age
0     Arun  45000.0  South   20
4     Ravi  48000.0  South   25

 Rename
      Name    Sales Region  Age
0     Arun  45000.0  South   20
1    Divya  52000.0  North   24
2  Karthik      NaN   East   21
3    Meena  61000.0   West   22
4     Ravi  48000.0  South   25

 Fill NA
      Name    Sales Region  Age
0     Arun  45000.0  South   20
1    Divya  52000.0  North   24
2  Karthik      0.0   East   21
3    Meena  6100